# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ dev ]

jobs:
  BuildAndDeploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: git config --global user.email "steven95421@gmail.com"
    - run: git config --global user.name "steven95421"
    - shell: bash
      env:
        GH_TOKEN: ${{ secrets.NODE_JS }}
      run: |
        npm run deploy
